# Generated by Django 5.0 on 2024-04-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='category')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
            ],
        ),
    ]
